FROM arm64v8/alpine:3.21@sha256:1ac9956f684d71081e18ee3d009e8743a713d1673d0d9625ed18891fecef123d

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-cancel-previous-builds"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-cancel-previous-builds"

ADD release/linux/arm64/drone-cancel-previous-builds /bin/
ENTRYPOINT ["/bin/drone-cancel-previous-builds"]
