FROM arm64v8/alpine:3.15@sha256:76467a0fb072205433a0596be103d4555357fced110dfc06ae74d16045ec5fc3

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-cancel-previous-builds"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-cancel-previous-builds"

ADD release/linux/arm64/drone-cancel-previous-builds /bin/
ENTRYPOINT ["/bin/drone-cancel-previous-builds"]
