FROM alpine:3.17@sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-cancel-previous-builds"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-cancel-previous-builds"

ADD release/linux/amd64/drone-cancel-previous-builds /bin/
ENTRYPOINT ["/bin/drone-cancel-previous-builds"]
