FROM alpine:3.21@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-cancel-previous-builds"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-cancel-previous-builds"

ADD release/linux/amd64/drone-cancel-previous-builds /bin/
ENTRYPOINT ["/bin/drone-cancel-previous-builds"]
