FROM arm64v8/alpine:3.18@sha256:30e6d35703c578ee703230b9dc87ada2ba958c1928615ac8a674fcbbcbb0f281

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-cancel-previous-builds"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-cancel-previous-builds"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-cancel-previous-builds"

ADD release/linux/arm64/drone-cancel-previous-builds /bin/
ENTRYPOINT ["/bin/drone-cancel-previous-builds"]
